### PR TITLE
penn/marc gets cho_date_range_norm

### LINKED ISSUE #243: Normalize Penn marc dates for date slider (cho_date_range_norm)
To populate cho_date_range_norm for Penn marc data:

```
    to_field "cho_date_range_norm", extract_marc("008[06-14]"), marc_date_range
```

### PR DESCRIPTION
**Pull request by aaron-collier**
Note that this is @ndushay's work that I accidentally merged early (before @jacobthill's review) and reverted made it impossible to restore the branch... 

## Why was this change made?

penn/marc collection gets populated `cho_date_range_norm` field.   

I coded this, rather than leaving it for Jacob, because I wanted to make sure the new macro worked in situ, and because I wasn't sure if Jacob was already conversant with the specific byte parsing of MARC control fields.  (And frankly, who would want to be?)

Must have @jacobthill's approval after he has a chance to vet the resulting output.

## Was the documentation (README, API, wiki, ...) updated?

n/a

closes #243

### CODE REVIEW

**Comment by jacobthill** [comment]
@ndushay There seem to be some unexpected changes to the dates.

- ['r19701916'] => [1934]
- ['r19uu1922'] => [1934]

Can you confirm that these are the expected dates? Maybe I'm misinterpreting it.

**Comment by ndushay** [comment]
@jacobthill do you have record ids for the problem children?

**Comment by jacobthill** [comment]
@ndushay 6053936 and 6071722 I think including 'r' second date would be okay.

**Comment by ndushay** [comment]
@jacobthill this now copes with date_type "r" and "e" 

@aaron-collier still needs Jacob's approval first, but wanna review again?

**Comment by aaron-collier** [comment]
@ndushay lol, I can't review my own apparently... but I'm happy to merge once @jacobthill tests.

**Pull request merged**
