### PR TITLE
Revert "Revert "Merge pull request #669 from sul-dlss/aub""

### PR DESCRIPTION
**Pull request by jcoyne**
This reverts commit 9970bda5e38c7930bc957beba796010e99ba69a1.

### CODE REVIEW

**Comment by ndushay** [comment]
@jcoyne can this revert PR be closed and the branch deleted?  It doesn't say why a reversion was made.

**Comment by jcoyne** [comment]
@ndushay this is a double revert. So, this restores changes Jacob made.

**Comment by ndushay** [comment]
um ... I just got dep updates deployed for dlme-transform.   So @jacobthill is it okay if this fix goes out with dep updates next week?

**Comment by jacobthill** [comment]
Next week is fine. Thanks @ndushay

**Pull request merged**
