### PR TITLE
Revise Sakip Sabanci mapping, fixes #356

### LINKED ISSUE #356: Check, revise, and transform Sakip Sabanci
After significant changes to the IR, it is necessary to check, possibly revise, re-transform, and re-load the Sakip Sabanci data sets.

### PR DESCRIPTION
**Pull request by jacobthill**
## Why was this change made?

- revise Sakip Sabanci mapping

## Was the documentation (README, API, wiki, ...) updated?

n/a

### CODE REVIEW

**Comment by jacobthill** [comment]
@ndushay I haven't figured out a way to map the cho_has_type field yet. This can only be mapped when the collections are somewhat homogenous. I have an open ticket to translate the Turkish types to English and then use existing translation maps to map the English to Arabic. When I work on that I will try to see if I can map the cho_has_type field but I think it can be merged for now.

**Comment by ndushay** [comment]
@jacobthill lang code for ?? turkish ?? incorrect, as circleci says:

```
<RuntimeError: error raised mapping sakip-sabanci: Traject::Indexer::ConfigLoadError: Error loading ..._configs/sakip_sabanci_common_config.rb:29 RuntimeError:tr is not an acceptable BCP47 language code>
```

**Comment by jacobthill** [comment]
@mjgiarlo Do you know why we are getting this error. I believe `tr` is the correct language code for Turkish. I think we did something to call this error for all language fields that were not explicitly validated by us (like by adding them in a translation map or something) but I can't find where we might have done that. I thought I asked you to do this so I wouldn't pass the wrong language field by mistake without any warning. Does this sound familiar at all?

**Comment by mjgiarlo** [comment]
@jacobthill It's because `tr` is not in this list: https://github.com/sul-dlss/dlme-transform/blob/master/config/settings.yml#L13-L21

**Comment by mjgiarlo** [comment]
Blocked by https://github.com/sul-dlss/dlme-transform/pull/395

**Pull request merged**
