### PR TITLE
Adds Honeybadger 

### LINKED ISSUE #750: Add honeybadger to dlme-transform
We currently only have logging and no method of notification on failure. If a transformation fails, or has any errors, the way to determine that would be to review the large logs on Cloudwatch, by alerting via honeybadger we can better indicate individual record failures during the transform step.

### PR DESCRIPTION
**Pull request by jermnelson**
## Why was this change made?
FIXES #750 

## How was this change tested?
Unit tests 

## Which documentation and/or configurations were updated?
See [comment](https://github.com/sul-dlss/dlme-transform/issues/750#issuecomment-882872163) on original ticket, need to figure out how to include HB API key (circle-ci build/env variables vs. adding hb yml using `shared_config`. Once determined, will add another commit.

### CODE REVIEW

**Comment by jermnelson** [comment]
All three instances of Honeybadger are now tested so not sure why Codeclimate is still complaining.

**Review by jmartin-sul — CHANGES_REQUESTED** [review]
more thorough review forthcoming, but for the time being:  i was curious about what felt like some inconsistencies in the new `require` statements (e.g. some modified specs had them but some didn't).  in playing around with pulling what seemed like unnecessary `require`s at first glance, i ran into some failing tests, but then playing around w/ the CLI script manually and reading the HB docs, i think i figured it out.  wil have a PR to this PR and review of the rest of this PR in a bit, but wanted to hold merging for now because i don't think this'll work quite as intended.

**Review by jmartin-sul — COMMENTED** [review]
i took a shot at trying to figure out the `require` and `expect` issues i think i found, and i think i made some progress, but my PR is failing CI (despite passing for me locally):  https://github.com/sul-dlss/dlme-transform/pull/761

**Comment by jermnelson** [comment]
Closing in favor of https://github.com/sul-dlss/dlme-transform/pull/761

**Pull request closed without merging**
