### PR TITLE
EachRecord.convert_to_language_hash: log an error when there's no language key

### PR DESCRIPTION
**Pull request by jmartin-sul**
also, small refactor to DRY up error message copypasta using a string template

## Why was this change made?

add logging to determine how frequently our transformation output is missing language.

ref #675

## How was this change tested?

existing unit tests for regressions, run transform locally over entirety of dlme-metadata and send output to log file, look for instances of the new log message

## Which documentation and/or configurations were updated?

n/a

### CODE REVIEW

**Comment by jmartin-sul** [comment]
here's a grep for the new log message that catches missing language when running the transform script:

[missing_language_key_errors.log](https://github.com/sul-dlss/dlme-transform/files/6866657/missing_language_key_errors.log)

this is the transform output from `exe/transform -w` run across the entirety of [dlme-metadata](https://github.com/sul-dlss/dlme-metadata), filtered for the error message added in this PR.

looks like there are currently 610 occurrences of this issue.

**Comment by jmartin-sul** [comment]
rebased on main after #766 was merged, but getting a new failure, described here:  https://github.com/sul-dlss/dlme-transform/issues/675#issuecomment-887914002

**Comment by jmartin-sul** [comment]
rebased on main after #770 was merged, new error described here: https://github.com/sul-dlss/dlme-transform/issues/675#issuecomment-888643003

**Comment by jmartin-sul** [comment]
will rebase and take out of draft once #776 is merged

**Review by aaron-collier — APPROVED** [review]

**Pull request merged**
